global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your-email@gmail.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'

route:
  group_by: ['alertname']
  receiver: 'slack-notifications'
  routes:
    - match:
        alertname: 'HighCPUUsage'
      receiver: 'email-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts'

  - name: 'email-notifications'
    email_configs:
      - to: 'recipient@example.com'
