
global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'yourmail@gmail.com'
  smtp_auth_username: 'yourmail@gmail.com'
  smtp_auth_password: 'your mail app password'

route:
  group_by: ['alertname']
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'  # default fallback

  routes:
    - match:
        alertname: 'HighCPUUsage'
      receiver: 'email-notifications'
      continue: true

    - match:
        alertname: 'HighCPUUsage'
      receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'slack_webhook_url'
        channel: '#alerts'
        send_resolved: true
        title: '{{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'

  - name: 'email-notifications'
    email_configs:
      - to: 'email-to-recievce notifications'
        send_resolved: true

