
global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'imkool.memes69@gmail.com'
  smtp_auth_username: 'imkool.memes69@gmail.com'
  smtp_auth_password: 'nviw awqm ofel jwid'

route:
  group_by: ['alertname']
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'  # default fallback

  routes:
    - match:
        alertname: 'HighCPUUsage'
      receiver: 'email-notifications'
      continue: true

    - match:
        alertname: 'HighCPUUsage'
      receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alerts'
        send_resolved: true
        title: '{{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'

  - name: 'email-notifications'
    email_configs:
      - to: 'everydaynormalguy0690@gmail.com'
        send_resolved: true

