groups:
  - name: alert.rules
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU Usage Detected"
          description: "Instance {{ $labels.instance }} CPU > 80% for 1 min"
